name: hetunet
channels:
  - pytorch
  - defaults
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pip:
    - -i https://pypi.tuna.tsinghua.edu.cn/simple
    - -r requirements.txt
